server:
  port: 8080


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


springdoc:
  swagger-ui:
    urls:
      - name: booking-service
        url: /booking-service/v3/api-docs
      - name: hotel-management-service
        url: /hotel-management-service/v3/api-docs